// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdwkqcacorowgdgsbfik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkd2txY2Fjb3Jvd2dkZ3NiZmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTcwMjUsImV4cCI6MjA1ODU5MzAyNX0.zU6mNFAPLbWUa6pvTWJeqe53b4MOJQLQDvIt9s8lod8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);